-- where in 사용
SELECT COUNT(*) AS FISH_COUNT 
FROM FISH_INFO 
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE 
    FROM FISH_NAME_INFO 
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
);

-- join 사용 (추가)
SELECT COUNT(*) AS FISH_COUNT 
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');
